[package]
name = "propaganda-filter"
version = "0.1.0"
authors = ["六翁 <lu.hl@alibaba-inc.com>"]
edition = "2018"

[lib]
name = "propaganda_filter"
path = "src/propagate_headers.rs"
crate-type = ["cdylib"]

[dependencies]
proxy-wasm = "0.1.3"
serde_json = "1.0.62"
log = "0.4.14"