version: '2'
services:
  proxy:
    build:
      context: ./config/envoy
      dockerfile: Dockerfile.proxy.local
    volumes:
      - ./config/envoy/envoy-local-wasm.yaml:/etc/envoy-local-wasm.yaml
      - ./target/wasm32-unknown-unknown/release/propaganda_filter.wasm:/etc/propaganda_filter.wasm
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"
  web_service:
    image: hashicorp/http-echo
    command:
      - '-text="propaganda_filter is here."'
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "5678"
    ports:
      - "18080:5678"
networks:
  envoymesh:
    external: true