version: '2'
services:
  proxy:
    build:
      context: ./envoy
      # switch to use local or remote
      # dockerfile: Dockerfile.proxy.local
      dockerfile: Dockerfile.proxy.remote
    volumes:
      - ./envoy/envoy-remote-wasm-2.yaml:/etc/envoy-remote-wasm.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"
  web_service:
    image: hashicorp/http-echo
    command:
      - '-text="propaganda_filter is here."'
    networks:
      envoymesh:
        aliases:
          - web_service
    expose:
      - "5678"
    ports:
      - "18080:5678"
networks:
  envoymesh:
    external: true